import { test } from "node:test"
import assert from "node:assert/strict"
import { OlxClient, retryAfterMs } from "../src/modules/olx/lib/client.ts"
import { olxUrls } from "../src/modules/olx/lib/constants.ts"
import { OlxApiError, OlxUnknownResultError, OlxWriteBlockedError } from "../src/modules/olx/lib/errors.ts"

const logger = { info() {}, warn() {}, error() {}, debug() {} } as never

function client(): OlxClient {
  return new OlxClient({
    clientId: "client",
    clientSecret: "client-secret-value",
    redirectUri: "https://api.example.com/olx/callback",
    urls: olxUrls("pl"),
    requestsPerMinute: 6000,
    timeoutMs: 5000,
    userAgent: "test",
    logger,
  })
}

type Call = { url: string; method: string; headers: Record<string, string>; body?: string }

function withFetch(answer: (call: Call) => Response | Promise<Response>): { calls: Call[]; restore: () => void } {
  const original = globalThis.fetch
  const calls: Call[] = []
  globalThis.fetch = (async (url: string | URL, init?: RequestInit) => {
    const call = { url: String(url), method: init?.method ?? "GET", headers: (init?.headers ?? {}) as Record<string, string>, body: init?.body as string | undefined }
    calls.push(call)
    return answer(call)
  }) as typeof fetch
  return { calls, restore: () => (globalThis.fetch = original) }
}

test("consent URL carries the scope the writers need", () => {
  const url = new URL(client().authorizeUrl("state123", "read write v2"))
  assert.equal(url.origin + url.pathname, "https://www.olx.pl/oauth/authorize/")
  assert.equal(url.searchParams.get("scope"), "read write v2")
  assert.equal(url.searchParams.get("state"), "state123")
  assert.equal(url.searchParams.get("redirect_uri"), "https://api.example.com/olx/callback")
})

test("writes: one attempt, the Version header, and every answer mapped to what a writer may do", async () => {
  const c = client()
  const answers: Response[] = [
    new Response(null, { status: 204 }),
    new Response(JSON.stringify({ error: { status: 400, title: "Invalid request", detail: "Data validation error occurred", validation: [{ field: "ad", title: "Ad has to be active" }] } }), { status: 400 }),
    new Response("<html>bad gateway</html>", { status: 502 }),
    new Response("slow down", { status: 429 }),
    new Response("<H1>403 ERROR</H1> Request blocked. Generated by cloudfront (CloudFront)", { status: 403 }),
  ]
  const f = withFetch(() => answers.shift() as Response)
  try {
    const body = { command: "deactivate", is_success: false }
    assert.equal(await c.send("POST", "/adverts/1012345678/commands", body, "token", ["lifecycle"]), null)
    assert.equal(f.calls[0].headers.Version, "2.0")
    assert.equal(f.calls[0].headers["Content-Type"], "application/json")
    await assert.rejects(c.send("POST", "/adverts/1012345678/commands", body, "token", ["lifecycle"]), (err: unknown) => {
      assert.ok(err instanceof OlxApiError)
      assert.equal(err.status, 400)
      assert.deepEqual(err.validation, [{ field: "ad", title: "Ad has to be active" }])
      return true
    })
    await assert.rejects(c.send("POST", "/adverts/1012345678/commands", body, "token", ["lifecycle"]), OlxUnknownResultError)
    await assert.rejects(c.send("POST", "/adverts/1012345678/commands", body, "token", ["lifecycle"]), (err: unknown) => err instanceof OlxApiError && err.status === 429)
    await assert.rejects(c.send("POST", "/adverts/1012345678/commands", body, "token", ["lifecycle"]), (err: unknown) => err instanceof OlxApiError && err.blocked)
    assert.equal(f.calls.length, 5, "never retried")
  } finally {
    f.restore()
  }
})

test("writes: a network failure is unknown, an unarmed writer never reaches the network", async () => {
  const c = client()
  const f = withFetch(() => {
    throw new TypeError("fetch failed")
  })
  try {
    await assert.rejects(c.send("PUT", "/adverts/1012345678", { title: "x" }, "token", ["price"]), OlxUnknownResultError)
    const before = f.calls.length
    await assert.rejects(c.send("PUT", "/adverts/1012345678", { title: "x" }, "token", ["lifecycle"]), OlxWriteBlockedError)
    await assert.rejects(c.send("POST", "/adverts/1012345678/commands", { command: "extend" }, "token", ["lifecycle"]), OlxWriteBlockedError)
    assert.equal(f.calls.length, before, "the barrier stops them before fetch")
  } finally {
    f.restore()
  }
})

test("reads: no Content-Type on GET, the IP block is not retried", async () => {
  const c = client()
  const f = withFetch(() => new Response("Request blocked. cloudfront", { status: 403 }))
  try {
    await assert.rejects(c.get("/adverts", { limit: "50" }, "token"), (err: unknown) => err instanceof OlxApiError && err.blocked)
    assert.equal(f.calls.length, 1)
    assert.equal(f.calls[0].headers["Content-Type"], undefined, "OLX answers 400 to a GET with Content-Type")
  } finally {
    f.restore()
  }
  assert.equal(retryAfterMs("30"), 30_000)
  assert.equal(retryAfterMs("9999"), 120_000)
  assert.equal(retryAfterMs("Wed, 21 Oct 2026 07:28:00 GMT"), null)
  assert.equal(retryAfterMs(null), null)
})
