import { test } from "node:test"
import assert from "node:assert/strict"
import { classifyError, describeValidation, looksLikeIpBlock, OlxApiError, OlxUnknownResultError, parseValidation } from "../src/modules/olx/lib/errors.ts"
import { parseStatistics, pickForStats, totalStats } from "../src/modules/olx/lib/stats.ts"
import { parseThreads, threadTotals } from "../src/modules/olx/lib/threads.ts"

test("statistics: read at the top level or inside data, broken numbers stay null", () => {
  assert.deepEqual(parseStatistics({ advert_views: 123, phone_views: 100, users_observing: 10 }), { views: 123, phoneViews: 100, observers: 10 })
  assert.deepEqual(parseStatistics({ data: { advert_views: "7", phone_views: null, users_observing: -1 } }), { views: 7, phoneViews: null, observers: null })
  assert.equal(parseStatistics({}), null)
  assert.equal(parseStatistics(null), null)
})

test("statistics: live adverts only, never read first, then the oldest, capped", () => {
  const now = new Date("2026-10-06T12:00:00Z")
  const hour = 60 * 60 * 1000
  const adverts = [
    { id: "a", olxId: "1", status: "active", statsAt: new Date(now.getTime() - 10 * hour) },
    { id: "b", olxId: "2", status: "active", statsAt: null },
    { id: "c", olxId: "3", status: "active", statsAt: new Date(now.getTime() - 1 * hour) },
    { id: "d", olxId: "4", status: "limited", statsAt: null },
    { id: "e", olxId: "5", status: "active", statsAt: new Date(now.getTime() - 20 * hour) },
  ]
  assert.deepEqual(pickForStats(adverts, now, 6 * hour, 10).map((a) => a.id), ["b", "e", "a"])
  assert.deepEqual(pickForStats(adverts, now, 6 * hour, 2).map((a) => a.id), ["b", "e"])
  const totals = totalStats([
    { status: "active", views: 10, phoneViews: 1, observers: 2, statsAt: "2026-10-06T10:00:00Z" },
    { status: "active", views: 5, phoneViews: null, observers: 1, statsAt: "2026-10-05T10:00:00Z" },
    { status: "outdated", views: 999, phoneViews: 9, observers: 9, statsAt: "2026-10-05T10:00:00Z" },
    { status: "active", views: null, phoneViews: null, observers: null, statsAt: null },
  ])
  assert.deepEqual(totals, { views: 15, phoneViews: 1, observers: 3, withStats: 2, oldestAt: "2026-10-05T10:00:00.000Z" })
})

test("threads: uuid preferred, counts only, the buyer id is not kept", () => {
  const raw = [
    { id: 1, uuid: "550e8400-e29b-41d4-a716-446655440000", advert_id: 1012345678, interlocutor_id: 777, total_count: 4, unread_count: 2, created_at: "2018-01-30 08:26:36", is_favourite: true },
    { id: 2, advert_id: null, interlocutor_id: 778, total_count: 1, unread_count: 0, created_at: "bad" },
    { uuid: "", id: null },
  ]
  const threads = parseThreads(raw)
  assert.equal(threads.length, 2)
  assert.deepEqual(threads[0], {
    key: "550e8400-e29b-41d4-a716-446655440000",
    advertId: "1012345678",
    unread: 2,
    total: 4,
    createdAt: "2018-01-30T08:26:36.000Z",
    favourite: true,
  })
  assert.equal(threads[1].key, "2")
  assert.equal(threads[1].createdAt, null)
  assert.ok(!JSON.stringify(threads).includes("777"), "no interlocutor id")
  assert.deepEqual(parseThreads({ data: raw }).length, 2)
  assert.deepEqual(threadTotals(threads), { threads: 2, unreadThreads: 1, unreadMessages: 2 })
})

test("errors: what a writer may do after each answer", () => {
  assert.equal(classifyError(new OlxUnknownResultError("POST /adverts", new Error("timeout"))), "unknown")
  assert.equal(classifyError(new OlxApiError(429, "slow down", true)), "throttled")
  assert.equal(classifyError(new OlxApiError(403, "blocked", false, { blocked: true })), "throttled")
  assert.equal(classifyError(new OlxApiError(401, "token", false)), "auth")
  assert.equal(classifyError(new OlxApiError(404, "gone", false)), "not_found")
  assert.equal(classifyError(new OlxApiError(400, "invalid", false)), "rejected")
  assert.equal(classifyError(new OlxApiError(403, "not yours", false)), "rejected")
  assert.equal(classifyError(new Error("boom")), "transient")
  assert.equal(looksLikeIpBlock(403, "<H1>403 ERROR</H1> Request blocked. Generated by cloudfront (CloudFront)"), true)
  assert.equal(looksLikeIpBlock(403, '{"error":{"title":"Forbidden"}}'), false)
  assert.equal(looksLikeIpBlock(500, "Request blocked"), false)
})

test("errors: validation issues from the documented error body", () => {
  const body = {
    error: {
      status: 400,
      title: "Invalid request",
      detail: "Data validation error occurred",
      validation: [
        { field: "title", title: "Too many capital letters" },
        { field: "ad", title: "Ad has to be active" },
      ],
    },
  }
  const parsed = parseValidation(body)
  assert.equal(parsed.detail, "Data validation error occurred")
  assert.equal(parsed.issues.length, 2)
  assert.equal(describeValidation(parsed.detail, parsed.issues), "Data validation error occurred: title: Too many capital letters; ad: Ad has to be active")
  assert.equal(parseValidation({ data: body }).issues.length, 2, "sometimes wrapped in data")
  assert.deepEqual(parseValidation({ error: "invalid_grant" }), { detail: "invalid_grant", issues: [] })
})
