// GENERATED by scripts/kit.mjs from package.json (kit 1.0.0). Do not edit here: change package.json and run `npm run kit:sync`.
/** Who this build is: the setup prompt pins this version, the manifest names it. */
export const KIT_META = {
  ns: "subiekt",
  pkg: "@koda-plus/medusa-plugin-subiekt-nexo",
  version: "0.2.1",
  kit: "1.0.0",
  name: "Subiekt nexo",
} as const
