import { STATE_TEXTS } from "./kit-contract"

/**
 * The words of the koda.integration/1 answers (one line per order and per
 * customer, the document and buyer facts, the board counters), in the
 * `integration` subtree of the admin dictionaries. The server uses them for
 * the fallback sentence; `en.ts` and `pl.ts` mount them as `integration`, so
 * a host translates the same keys with the plugin dictionary.
 *
 * Plain text here: the Polish dictionary goes through typeset() as a whole.
 */

export const integrationEn = {
  ...STATE_TEXTS.en,
  kind: {
    vat: "VAT invoice",
    proforma: "Proforma",
    receipt: "Receipt",
    correction: "Correction",
  },
  order: {
    failed: "Document not issued",
    correctionFailed: "Correction not issued",
    unknown: "Not known if the document was issued",
    ksefRejected: "Rejected by KSeF",
    needsCorrection: "Needs a correction",
    correctionToApprove: "Correction to approve",
    correctionManual: "Correction to handle by hand",
    correctionWaitsWriter: "Approved correction waits for the writer",
    rejectFailed: "Proforma of a canceled order still active",
    emailFailed: "E-mail to the buyer not sent",
    buyerWarning: "Issued for a consumer: check the NIP",
    unpaidOverdue: "Unpaid since {{date}}",
    toIssue: "To issue",
    issuing: "Being issued",
    ksefProcessing: "Waiting for KSeF",
    emailWaiting: "E-mail waits for the KSeF number",
    issued: "{{document}}",
    canceled: "{{document}}: rejected",
    waitingPayment: "Waits for the payment",
    canceledNone: "Order canceled, no document",
    notConfigured: "Fakturownia is not set up",
    more_one: "and {{count}} more to look at",
    more_other: "and {{count}} more to look at",
    demo: "Sample data of the demo mode",
  },
  customer: {
    failed_one: "{{count}} order with a document problem",
    failed_other: "{{count}} orders with a document problem",
    attention_one: "{{count}} order waits for a person",
    attention_other: "{{count}} orders wait for a person",
    active: "Documents being issued",
    ok_one: "{{count}} document issued",
    ok_other: "{{count}} documents issued",
    none: "No documents yet",
  },
  fact: {
    document: "{{document}}",
    documentPending: "{{kind}} being issued",
    documentFailed: "{{kind}}: not issued",
    documentUnknown: "{{kind}}: result of the issue unknown",
    documentToIssue: "To issue",
    documentCanceled: "{{document}}: rejected",
    lastDocument: "Last: {{document}}",
    ksefAccepted: "KSeF {{number}}",
    ksefAcceptedNoNumber: "Accepted by KSeF",
    ksefProcessing: "Waiting for KSeF",
    ksefRejected: "Rejected by KSeF",
    ksefOffline: "Issued offline, waiting for KSeF",
    ksefNotSent: "Not sent to KSeF",
    paid: "Paid",
    unpaid: "Unpaid",
    issuedOn: "Issued {{date}}",
    buyerCompany: "Company, NIP on the invoice",
    buyerPerson: "Consumer",
    buyerInvalidNip: "Consumer: the NIP was not valid",
    buyerNoNip: "Consumer: a company without a NIP",
    buyerReceiptNip: "Consumer on the receipt, the NIP came later",
  },
  attention: {
    documents_attention: "Documents needing attention",
    corrections_to_approve: "Corrections to approve",
    ksef_problems: "Rejected by KSeF",
    to_issue: "To issue",
  },
  problem: {
    not_configured: "No API token or account: no document is issued",
    demo: "Demo mode: a simulated Fakturownia account, nothing leaves Medusa",
  },
}

export const integrationPl = {
  ...STATE_TEXTS.pl,
  kind: {
    vat: "Faktura VAT",
    proforma: "Proforma",
    receipt: "Paragon",
    correction: "Korekta",
  },
  order: {
    failed: "Dokument niewystawiony",
    correctionFailed: "Korekta niewystawiona",
    unknown: "Nie wiadomo, czy dokument powstał",
    ksefRejected: "Odrzucony przez KSeF",
    needsCorrection: "Wymaga korekty",
    correctionToApprove: "Korekta do zatwierdzenia",
    correctionManual: "Korekta do obsłużenia ręcznie",
    correctionWaitsWriter: "Zatwierdzona korekta czeka na włączenie zapisu",
    rejectFailed: "Proforma anulowanego zamówienia wciąż aktywna",
    emailFailed: "E-mail do nabywcy niewysłany",
    buyerWarning: "Wystawiono dla konsumenta: sprawdź NIP",
    unpaidOverdue: "Nieopłacony od {{date}}",
    toIssue: "Do wystawienia",
    issuing: "W trakcie wystawiania",
    ksefProcessing: "Czeka na KSeF",
    emailWaiting: "E-mail czeka na numer KSeF",
    issued: "{{document}}",
    canceled: "{{document}}: odrzucono",
    waitingPayment: "Czeka na płatność",
    canceledNone: "Zamówienie anulowane, bez dokumentu",
    notConfigured: "Fakturownia nie jest skonfigurowana",
    more_one: "i jeszcze {{count}} sprawa do sprawdzenia",
    more_few: "i jeszcze {{count}} sprawy do sprawdzenia",
    more_many: "i jeszcze {{count}} spraw do sprawdzenia",
    more_other: "i jeszcze {{count}} sprawy do sprawdzenia",
    demo: "Przykładowe dane trybu demo",
  },
  customer: {
    failed_one: "{{count}} zamówienie z problemem dokumentu",
    failed_few: "{{count}} zamówienia z problemem dokumentu",
    failed_many: "{{count}} zamówień z problemem dokumentu",
    failed_other: "{{count}} zamówienia z problemem dokumentu",
    attention_one: "{{count}} zamówienie czeka na człowieka",
    attention_few: "{{count}} zamówienia czekają na człowieka",
    attention_many: "{{count}} zamówień czeka na człowieka",
    attention_other: "{{count}} zamówienia czekają na człowieka",
    active: "Dokumenty w trakcie wystawiania",
    ok_one: "{{count}} wystawiony dokument",
    ok_few: "{{count}} wystawione dokumenty",
    ok_many: "{{count}} wystawionych dokumentów",
    ok_other: "{{count}} wystawionego dokumentu",
    none: "Jeszcze bez dokumentów",
  },
  fact: {
    document: "{{document}}",
    documentPending: "{{kind}} w trakcie wystawiania",
    documentFailed: "{{kind}}: nie wystawiono",
    documentUnknown: "{{kind}}: wynik wystawienia nieznany",
    documentToIssue: "Do wystawienia",
    documentCanceled: "{{document}}: odrzucono",
    lastDocument: "Ostatni: {{document}}",
    ksefAccepted: "KSeF {{number}}",
    ksefAcceptedNoNumber: "Przyjęty w KSeF",
    ksefProcessing: "Czeka na KSeF",
    ksefRejected: "Odrzucony przez KSeF",
    ksefOffline: "Wystawiony offline, czeka na KSeF",
    ksefNotSent: "Niewysłany do KSeF",
    paid: "Opłacony",
    unpaid: "Nieopłacony",
    issuedOn: "Wystawiony {{date}}",
    buyerCompany: "Firma, NIP na fakturze",
    buyerPerson: "Konsument",
    buyerInvalidNip: "Konsument: NIP był nieprawidłowy",
    buyerNoNip: "Konsument: firma bez NIP",
    buyerReceiptNip: "Konsument na paragonie, NIP przyszedł później",
  },
  attention: {
    documents_attention: "Dokumenty wymagające uwagi",
    corrections_to_approve: "Korekty do zatwierdzenia",
    ksef_problems: "Odrzucone przez KSeF",
    to_issue: "Do wystawienia",
  },
  problem: {
    not_configured: "Brak tokenu API albo konta: żaden dokument nie jest wystawiany",
    demo: "Tryb demo: symulowane konto Fakturowni, nic nie wychodzi z Medusy",
  },
}

/* Polish has more plural forms than English; every English key must exist in Polish. */
const samePolishKeys: typeof integrationEn = integrationPl
void samePolishKeys
