// GENERATED by scripts/kit.mjs from package.json (kit 1.0.1). Do not edit here: change package.json and run `npm run kit:sync`.
/** Who this build is: the setup prompt pins this version, the manifest names it. */
export const KIT_META = {
  ns: "olx",
  pkg: "@koda-plus/medusa-plugin-olx",
  version: "0.2.1",
  kit: "1.0.1",
  name: "OLX",
} as const
