#!/usr/bin/env node
/**
 * The shared kit (kit/) is the only source of the code every plugin has in
 * common: the koda.integration/1 contract, its server routes and guards, the
 * admin fetch, registry and card frame, the page kit (guide) and the
 * community strings. This script writes namespaced copies into each package,
 * so packages stay self-contained (no runtime dependency, `vendor` copies
 * them like any other file).
 *
 *   node scripts/kit.mjs sync [--only inpost,stripe]   write the copies
 *   node scripts/kit.mjs check                          fail on any drift
 *
 * Every copy starts with a GENERATED line. Edit kit/, then sync.
 */
import fs from "node:fs"
import path from "node:path"
import { listPackages, root, selectPackages } from "./lib/packages.mjs"

const KIT = path.join(root, "kit")
const KIT_VERSION = fs.readFileSync(path.join(KIT, "VERSION"), "utf8").trim()

/** kit file -> package file, `{ns}` and `{mod}` filled per package. */
const FILES = [
  ["contract.ts", "src/modules/{mod}/lib/kit-contract.ts"],
  ["server/routes.ts", "src/modules/{mod}/lib/kit-routes.ts"],
  ["server/guards.ts", "src/modules/{mod}/lib/kit-guards.ts"],
  ["admin/kit.tsx", "src/admin/lib/{ns}-kit.tsx"],
  ["admin/guide.tsx", "src/admin/lib/{ns}-guide.tsx"],
  ["admin/community.ts", "src/admin/lib/{ns}-kit-community.ts"],
  ["test/conformance.ts", "test/kit-conformance.ts"],
]

function header(from) {
  return `// GENERATED from kit/${from} (kit ${KIT_VERSION}) by scripts/kit.mjs. Do not edit here: change the kit and run \`npm run kit:sync\`.\n`
}

function render(p, from) {
  const text = fs.readFileSync(path.join(KIT, from), "utf8")
  return (
    header(from) +
    text
      .replaceAll("__MOD__", p.moduleDir)
      .replaceAll("__NS__", p.ns)
      .replaceAll("../../modules/" + p.ns + "/lib/kit-contract", "../../modules/" + p.moduleDir + "/lib/kit-contract")
      .replaceAll("__KIT_VERSION__", KIT_VERSION)
  )
}

function meta(p) {
  return [
    `// GENERATED by scripts/kit.mjs from package.json (kit ${KIT_VERSION}). Do not edit here: change package.json and run \`npm run kit:sync\`.`,
    "/** Who this build is: the setup prompt pins this version, the manifest names it. */",
    "export const KIT_META = {",
    `  ns: ${JSON.stringify(p.ns)},`,
    `  pkg: ${JSON.stringify(p.name)},`,
    `  version: ${JSON.stringify(p.version)},`,
    `  kit: ${JSON.stringify(KIT_VERSION)},`,
    `  name: ${JSON.stringify(p.brand)},`,
    "} as const",
    "",
  ].join("\n")
}

/** Every file the kit owns in a package, with its expected content. */
function planFor(p) {
  const out = []
  for (const [from, to] of FILES) {
    if (!fs.existsSync(path.join(KIT, from))) continue
    out.push([to.replaceAll("{ns}", p.ns).replaceAll("{mod}", p.moduleDir), render(p, from)])
  }
  out.push([`src/admin/lib/${p.ns}-kit-meta.ts`, meta(p)])
  out.push([`src/modules/${p.moduleDir}/lib/kit-meta.ts`, meta(p)])
  return out
}

const [command, ...rest] = process.argv.slice(2)
let only = null
const i = rest.indexOf("--only")
if (i >= 0) only = new Set(String(rest[i + 1] ?? "").split(",").map((s) => s.trim()).filter(Boolean))

if (command !== "sync" && command !== "check") {
  console.error("usage: node scripts/kit.mjs sync|check [--only inpost,stripe]")
  process.exit(1)
}

const packages = selectPackages(listPackages(), only)
let drift = 0
let written = 0
for (const p of packages) {
  for (const [rel, content] of planFor(p)) {
    const file = path.join(p.path, rel)
    const current = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null
    if (current === content) continue
    if (command === "check") {
      drift += 1
      console.error(`[kit] ${p.dir}/${rel}: ${current === null ? "missing" : "differs from the kit"}`)
    } else {
      fs.mkdirSync(path.dirname(file), { recursive: true })
      fs.writeFileSync(file, content)
      written += 1
      console.log(`[kit] ${p.dir}/${rel}`)
    }
  }
}

if (command === "check") {
  if (drift > 0) {
    console.error(`[kit] ${drift} file(s) out of date: run npm run kit:sync`)
    process.exit(1)
  }
  console.log(`[kit] ${packages.length} packages match kit ${KIT_VERSION}`)
} else {
  console.log(`[kit] kit ${KIT_VERSION}: ${written} file(s) written in ${packages.length} packages`)
}
